name: LOGIN

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    
      - name: Gettings files from Repo
        uses: actions/checkout@v2
      
      - name: Decrypt secret
        run: |-
            echo "${{ secrets.AGE_KEY }}" > fgo.txt
            export SOPS_AGE_KEY_FILE=$(pwd)/fgo.txt
            curl -LO https://github.com/getsops/sops/releases/download/v3.9.1/sops-v3.9.1.linux.amd64
            sudo mv sops-v3.9.1.linux.amd64 /usr/bin/sops
            sudo chmod +x /usr/bin/sops
            sops --decrypt auth.yaml > auth_file.yaml
        
      - name: Install Requirements
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Execute main script
        run: |
          source env/bin/activate
          python3 main.py
      
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions [Bot]"
                  
      - name: Commit files
        run: |
          git add ${{github.workspace}}/last_run_date.txt
          git commit --author="GitHub Actions [Bot] <github-actions[bot]@users.noreply.github.com>" -m "Commit last run"        
          git push origin main