name: LOGIN

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    
      - name: Gettings files from Repo
        uses: actions/checkout@v2
      
      - name: Decrypt secret
        run: |-
            echo "${{ secrets.AGE_KEY }}" > fgo.txt
            export SOPS_AGE_KEY_FILE=$(pwd)/fgo.txt
            curl -LO https://github.com/getsops/sops/releases/download/v3.9.1/sops-v3.9.1.linux.amd64
            sudo mv sops-v3.9.1.linux.amd64 /usr/bin/sops
            sudo chmod +x /usr/bin/sops
            sops --decrypt auth.yaml > auth_file.yaml
        
      - name: Install Requeriments
        run: |
          pip install -r requirements.txt

      - name: Execute main script 1
        run: |
          python3 main.py